"""initial

Revision ID: 0538a21b3e6f
Revises: 
Create Date: 2024-07-29 15:14:33.772480

"""
from typing import Sequence, Union

from alembic import op  # noqa: F401 
import sqlalchemy as sa  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = '0538a21b3e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
